from django.urls import path, re_path
from . import views
from .core import auth, error, properties, manage, search, new
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path("", views.popup, name="index"),
    path("home", views.index, name="index"),
    path("login", auth.elogin, name="login"),
    path("register", auth.register, name="register"),
    path("verify/<int:idd>", auth.verify, name="verify"),
    path("error", error.error, name="error"),
    path("logout", auth.elogout, name="logout"),
    path("my", properties.my, name="my"),
    path("staff", manage.staff, name="staff"),
    path("staff/view/<int:id>", manage.mstaff, name="search"),
    path("staff/search", search.staff, name="search"),
    path("contact", views.contact, name="contact"),
    path("new/property", new.property, name="new-property"),
    path("view/<int:id>", views.property, name="view-property"),
    path("manage", manage.property, name="manage-property"),
    path("new/paymentPlan/<int:id>", new.newPaymentPlan, name="add-paymentPlan"),
    path("remove/paymentPlan/<int:id>", new.rePaymentPlan, name="remove-paymentPlan"),
    path("remove/collum", new.rePlan, name="remove-col"),
    path("delete/<int:id>", new.rePro, name="remove-pro"),
    path("inv/<int:name>", views.inv, name="inv"),
    path("invsee/<int:id>", views.invsee, name="invsee"),
    path("msg", new.msg, name="msg"),
    path("info/<int:id>", views.info, name="info"),
    path("new/info", new.details, name="new info"),
    path("delete/info/<int:id>", views.delete, name="delete info"),
    path("manage/info", views.manage, name="manage users"),
    path("contact/book", new.book, name="book"),
    path("send/book", new.book_, name="book"),
    path("bank", views.bank, name="bank"),
    path("projects", views.projects, name="projects"),
    path("new/project", new.project, name="new project"),
    path("manage/sold", manage.sold, name="manage all sold properties"),
    path("manage/search/sold", search.sold, name="search all sold properties"),
    path("manage/search", search.inv, name="search all sold properties"),
    path("del/inv/<int:id>", manage.delInv, name="Delete inv"),
    path("del/proj/<int:id>", manage.delp, name="Delete project"),
    re_path(r"^.well-known/assetlinks\.json$", views.hidebar, name='well.json'),
    path("pass", auth.changePass, name="change password"),
    path("pass/verify/<int:id>", auth.changePassVer, name="change ver password"),
    path("new/ad", views.new_popup, name="new add"),
    path("delete/user/<int:id>", manage.delete_user, name="delete user"),
    path("edit/user/<int:id>", manage.edit_user, name="edit user"),
    path("forgot", auth.forgot, name="forgot password"),
    path("forgot/2/<str:cnic>", auth.forgot1, name="forgot password step 2"),
    path("forgot/3/<int:id>/<str:cnic>", auth.forgot2, name="forgot password step 3"),
    path("edit/info/<int:id>/", manage.edit_details, name="edit info"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
